
// This file is generated by Gemini.

'use server';

/**
 * @fileOverview A recipe generation AI agent.
 *
 * - generateRecipe - A function that handles the recipe generation process.
 * - GenerateRecipeInput - The input type for the generateRecipe function.
 * - GenerateRecipeOutput - The return type for the generateRecipe function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecipeInputSchema = z.object({
  ingredients: z
    .array(z.string())
    .describe('A list of ingredients to use in the recipe.'),
  cuisine: z
    .string()
    .optional()
    .describe('The type of cuisine for the recipe, e.g. Italian, Mexican, etc.'),
});

export type GenerateRecipeInput = z.infer<typeof GenerateRecipeInputSchema>;

const GenerateRecipeOutputSchema = z.object({
  title: z.string().describe('The title of the recipe. This title MUST accurately reflect the main ingredients provided.'),
  ingredients: z.array(z.string()).describe('The list of ingredients needed for the recipe, including amounts (e.g., "2 large potatoes, diced", "1 red onion, chopped").'),
  instructions: z.array(z.string()).describe('The step-by-step instructions for preparing the recipe.'),
  servings: z.string().optional().describe('The number of servings the recipe makes, e.g. "Serves 4".'),
  prepTime: z.string().optional().describe('The preparation time for the recipe, e.g. "Prep time: 15 minutes".'),
  cookTime: z.string().optional().describe('The cooking time for the recipe, e.g. "Cook time: 30 minutes".'),
  description: z.string().optional().describe('A short, appetizing description of the recipe, highlighting the main ingredients used from the provided list.'),
});

export type GenerateRecipeOutput = z.infer<typeof GenerateRecipeOutputSchema>;

export async function generateRecipe(input: GenerateRecipeInput): Promise<GenerateRecipeOutput> {
  return generateRecipeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateRecipePrompt',
  input: {schema: GenerateRecipeInputSchema},
  output: {schema: GenerateRecipeOutputSchema},
  prompt: `You are a world-class chef specializing in creating recipes based *only* on the ingredients provided. Your primary goal is to devise a recipe that prominently features these ingredients.

You will generate a recipe strictly using the ingredients listed below. The recipe title and description MUST accurately reflect these main ingredients. Do not introduce new primary ingredients. You may assume common pantry staples like oil, salt, pepper, and basic spices if not listed but absolutely necessary for the preparation, but the focus must remain on the provided ingredients.

Ingredients:
{{#each ingredients}}
- {{{this}}}
{{/each}}

{{#if cuisine}}
Your recipe should be in the style of {{cuisine}} cuisine.
{{/if}}

Please provide the recipe with the following fields, ensuring the title and description closely match the provided ingredients:
- title: The title of the recipe (e.g., "Potato and Onion Fry", "Spicy Chicken Stir-fry with Bell Peppers").
- ingredients: A list of all ingredients needed for the recipe, including amounts.
- instructions: Step-by-step instructions for preparing the recipe.
- servings: The number of servings the recipe makes.
- prepTime: The preparation time for the recipe.
- cookTime: The cooking time for the recipe.
- description: A short, appetizing description of the recipe, highlighting the main ingredients.
  `,
});

const generateRecipeFlow = ai.defineFlow(
  {
    name: 'generateRecipeFlow',
    inputSchema: GenerateRecipeInputSchema,
    outputSchema: GenerateRecipeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
